### ISSUE TITLE
[에러핸들링 추가 요청!] slack api 에서 request 가 empty할때 어떤 벨리데이션도 없어서 500 을 줍니다~

### ISSUE THREAD

**Issue by Nuung** [JAY-Chan9yu/emoji_rank#10]
안녕하세요~ 
저희 사내에서도 해당 project 기반으로 slack bot을 추가하면 어떨까 싶은 생각에 clone 해서 한 번 보고 있었습니다!

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/33516349/219866951-6955536a-4ac5-4e23-96bd-fd58d912ebc3.png">

`request_data = await request.json()` 부분 위 사진과 같이 exception check가 한 번하는게 어떨까요~?
POST: /slack/ 경우 request body가 empty할 때 `await request.json()` 에서 JSONDecodeError 를 뱉습니다~ 아무래도 pydantic 바로 request validation을 안하고 json casting 을 먼저하다 보니 어쩔 수 없이 이 경우엔 추가하는게 좋을 것 같습니다 :)

좋은 프로젝트 잘 보고 갑니다, 감사합니다.

**Comment by JAY-Chan9yu** [comment]
@Nuung 님 좋은 의견 감사드립니다!
처음 의도 자체는 slack을 통해서 들어오는 값들은 body가 존재할거라 그대로 두었는데
다른 경로(postman 등)로 직접 호출할 경우에는 에러가 발생할 수 있겠네요~

요거 @Nuung님 께서 PR을 올려주시는건 어떨까요? 제가 수정해도 되지만 오픈소스이기도 하고 이슈를 남겨주신 Nuung님께서 수정해주시는게 좀더  의미 있을것 같아요!

status_code는 403보다는 400에러를 던져주는건 어떨까요?

**Comment by Nuung** [comment]
@JAY-Chan9yu 

넵 :) 400으로 수정 후 P.R 올려두었습니다. 의도 하신 PR syntax에 벗어난 점 있으면 말씀해주세요!
좋은 프로젝트 감사합니다!
